version: "3.4"

services:
  nodeapp:
    image: nodeapp:latest
    build: .
    ports:
      - ${APP_PORT:-80}:80
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - mynet

  redis:
    container_name: redis
    networks:
      - mynet
    image: redis:6
    profiles:
      - with-redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      intervel: 10s
      timeout: 5s
      retries: 5


networks:
  mynet:


